spring.application.name=Vertex-Academy
spring.datasource.url=jdbc:mysql://${DB_HOST_VERTEX}:3306/${DB_NAME_VERTEX}
spring.datasource.username=${VERTEX_DB_USER}
spring.datasource.password=${VERTEX_DB_PASSWORD}
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true


server.error.include-stacktrace=never
API.KEY=VEX_BOT_API_KEY_VERTEX_ACADEMY